# Домашнее задание к занятию «3.2. Coroutines: Scopes, Cancellation, Supervision»

Выполненное задание прикрепите ссылкой на ваши GitHub-проекты в личном кабинете студента на сайте [netology.ru](https://netology.ru).

## Вопросы: Cancellation

### Вопрос №1

Отработает ли в этом коде строка `<--`? Поясните, почему да или нет.

### Ответ
Не отработает, так как родительская корутина отменяется раньше, чем запускаются дочерние, что приводит к их отмене.

```kotlin
fun main() = runBlocking {
    val job = CoroutineScope(EmptyCoroutineContext).launch {
        launch {
            delay(500)
            println("ok") // <--
        }
        launch {
            delay(500)
            println("ok")
        }
    }
    delay(100)
    job.cancelAndJoin()
}

```

### Вопрос №2

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Не отработает, так как к тому времени, как дочерняя корутина отработает, её уже отменили.

```kotlin
fun main() = runBlocking {
    val job = CoroutineScope(EmptyCoroutineContext).launch {
        val child = launch {
            delay(500)
            println("ok") // <--
        }
        launch {
            delay(500)
            println("ok")
        }
        delay(100)
        child.cancel()
    }
    delay(100)
    job.join()
}
```

## Вопросы: Exception Handling

### Вопрос №1

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Не отработает, так как блок try-catch поверх launch не перехватит никаких исключений.
Для перехвата исключения try должен быть внутри launch, а не наоборот.

```kotlin
fun main() {
    with(CoroutineScope(EmptyCoroutineContext)) {
        try {
            launch {
                throw Exception("something bad happened")
            }
        } catch (e: Exception) {
            e.printStackTrace() // <--
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №2

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Отработает, т.к. исключение выбрасывается внутри блока try-catch, расположенного внутри корутины.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        try {
            coroutineScope {
                throw Exception("something bad happened")
            }
        } catch (e: Exception) {
            e.printStackTrace() // <--
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №3

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Отработает, так как supervisorScope перехватит ошибку и передаст её в блок try-catch.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        try {
            supervisorScope {
                throw Exception("something bad happened")
            }
        } catch (e: Exception) {
            e.printStackTrace() // <--
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №4

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Не отработает, так как coroutineScope перехватит ошибку во второй дочерней корутине и передаст её в блок try-catch родительской корутины, после чего произойдёт отмена работы всех дочерних корутин.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        try {
            coroutineScope {
                launch {
                    delay(500)
                    throw Exception("something bad happened") // <--
                }
                launch {
                    throw Exception("something bad happened")
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №5

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Отработает, потому что supervisorScope не отменяет родительскую корутину при ошибке в дочерней. 
Соответственно, вторая дочерняя продолжает выполняться, пока в ней не возникнет ее собственная ошибка.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        try {
            supervisorScope {
                launch {
                    delay(500)
                    throw Exception("something bad happened") // <--
                }
                launch {
                    throw Exception("something bad happened")
                }
            }
        } catch (e: Exception) {
            e.printStackTrace() // <--
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №6

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Не отработает. Ошибка в родительской корутине вызовет отмену всех дочерних.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        CoroutineScope(EmptyCoroutineContext).launch {
            launch {
                delay(1000)
                println("ok") // <--
            }
            launch {
                delay(500)
                println("ok")
            }
            throw Exception("something bad happened")
        }
    }
    Thread.sleep(1000)
}
```

### Вопрос №7

Отработает ли в этом коде строка `<--`. Поясните, почему да или нет.

### Ответ
Не отработает. SupervisorJob не отменяет родительскую корутину при ошибках в дочерних, но так как ошибка произошла в родительской корутине, то все дочерние отменятся.

```kotlin
fun main() {
    CoroutineScope(EmptyCoroutineContext).launch {
        CoroutineScope(EmptyCoroutineContext + SupervisorJob()).launch {
            launch {
                delay(1000)
                println("ok") // <--
            }
            launch {
                delay(500)
                println("ok")
            }
            throw Exception("something bad happened")
        }
    }
    Thread.sleep(1000)
}
```
